SELECT (MAX(P.WEIGHT) + 1) AS MAX_PLUS_ONE FROM './examples/data/P.csv' AS P(PNO, PNAME, COLOR, WEIGHT, CITY) ;


SELECT MAX(P.WEIGHT)  FROM './examples/data/P.csv' AS P(PNO, PNAME, COLOR, WEIGHT, CITY) ;

SELECT MAX(P.WEIGHT) AS XXX FROM './examples/data/P.csv' AS P(PNO, PNAME, COLOR, WEIGHT, CITY) ;
