WITH 
MINIS (COLA,COLB)  
AS  
(SELECT S.SNO,S.SNAME FROM './examples/data/s.csv' AS S (SNO,SNAME,STATUS,CITY ) ) , 
MAXIS ( KOLA,KOLB ) 
AS  
(SELECT SP.SNO,SP.PART FROM './examples/data/sp.csv' AS SP ( SNO,PART,QTY) ) 

SELECT MAXIS.KOLA,MAXIS.KOLB FROM MAXIS AS MAXIS ( KOLA,KOLB ) ;  